/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAgentRegistry__factory } from "./IAgentRegistry__factory";
export { RiskRouter__factory } from "./RiskRouter__factory";
