/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace RiskRouter {
  export type TradeIntentStruct = {
    agentId: string;
    pair: string;
    volume: BigNumberish;
    maxPrice: BigNumberish;
    deadline: BigNumberish;
  };

  export type TradeIntentStructOutput = [
    agentId: string,
    pair: string,
    volume: bigint,
    maxPrice: bigint,
    deadline: bigint
  ] & {
    agentId: string;
    pair: string;
    volume: bigint;
    maxPrice: bigint;
    deadline: bigint;
  };
}

export interface RiskRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAgent"
      | "agentRegistry"
      | "authorizeTrade"
      | "authorizedAgents"
      | "eip712Domain"
      | "hashTradeIntent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "TradeAuthorized"
      | "TradeRejected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeTrade",
    values: [RiskRouter.TradeIntentStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashTradeIntent",
    values: [RiskRouter.TradeIntentStruct]
  ): string;

  decodeFunctionResult(functionFragment: "addAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashTradeIntent",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeAuthorizedEvent {
  export type InputTuple = [
    intentHash: BytesLike,
    agent: AddressLike,
    pair: string,
    volume: BigNumberish
  ];
  export type OutputTuple = [
    intentHash: string,
    agent: string,
    pair: string,
    volume: bigint
  ];
  export interface OutputObject {
    intentHash: string;
    agent: string;
    pair: string;
    volume: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeRejectedEvent {
  export type InputTuple = [intentHash: BytesLike, reason: string];
  export type OutputTuple = [intentHash: string, reason: string];
  export interface OutputObject {
    intentHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiskRouter extends BaseContract {
  connect(runner?: ContractRunner | null): RiskRouter;
  waitForDeployment(): Promise<this>;

  interface: RiskRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAgent: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  authorizeTrade: TypedContractMethod<
    [intent: RiskRouter.TradeIntentStruct, signature: BytesLike],
    [boolean],
    "nonpayable"
  >;

  authorizedAgents: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  hashTradeIntent: TypedContractMethod<
    [intent: RiskRouter.TradeIntentStruct],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeTrade"
  ): TypedContractMethod<
    [intent: RiskRouter.TradeIntentStruct, signature: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedAgents"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashTradeIntent"
  ): TypedContractMethod<
    [intent: RiskRouter.TradeIntentStruct],
    [string],
    "view"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "TradeAuthorized"
  ): TypedContractEvent<
    TradeAuthorizedEvent.InputTuple,
    TradeAuthorizedEvent.OutputTuple,
    TradeAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "TradeRejected"
  ): TypedContractEvent<
    TradeRejectedEvent.InputTuple,
    TradeRejectedEvent.OutputTuple,
    TradeRejectedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "TradeAuthorized(bytes32,address,string,uint256)": TypedContractEvent<
      TradeAuthorizedEvent.InputTuple,
      TradeAuthorizedEvent.OutputTuple,
      TradeAuthorizedEvent.OutputObject
    >;
    TradeAuthorized: TypedContractEvent<
      TradeAuthorizedEvent.InputTuple,
      TradeAuthorizedEvent.OutputTuple,
      TradeAuthorizedEvent.OutputObject
    >;

    "TradeRejected(bytes32,string)": TypedContractEvent<
      TradeRejectedEvent.InputTuple,
      TradeRejectedEvent.OutputTuple,
      TradeRejectedEvent.OutputObject
    >;
    TradeRejected: TypedContractEvent<
      TradeRejectedEvent.InputTuple,
      TradeRejectedEvent.OutputTuple,
      TradeRejectedEvent.OutputObject
    >;
  };
}
