/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as riskRouterSol from "./RiskRouter.sol";
export { MockRegistry__factory } from "./MockRegistry__factory";
