/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockRegistry,
  MockRegistryInterface,
} from "../../../src/contracts/MockRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "isRegisteredAgent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "bool",
        name: "status",
        type: "bool",
      },
    ],
    name: "setRegistered",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506102868061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c8063e21b38d214610038578063fc353ae514610068575b5f80fd5b610052600480360381019061004d919061018a565b610084565b60405161005f91906101cf565b60405180910390f35b610082600480360381019061007d9190610212565b6100d5565b005b5f805f8373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f9054906101000a900460ff169050919050565b805f808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020015f205f6101000a81548160ff0219169083151502179055505050565b5f80fd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f61015982610130565b9050919050565b6101698161014f565b8114610173575f80fd5b50565b5f8135905061018481610160565b92915050565b5f6020828403121561019f5761019e61012c565b5b5f6101ac84828501610176565b91505092915050565b5f8115159050919050565b6101c9816101b5565b82525050565b5f6020820190506101e25f8301846101c0565b92915050565b6101f1816101b5565b81146101fb575f80fd5b50565b5f8135905061020c816101e8565b92915050565b5f80604083850312156102285761022761012c565b5b5f61023585828601610176565b9250506020610246858286016101fe565b915050925092905056fea264697066735822122028acd0ab4ee1e6755db0cd2f23467619590d9c7c3baa440163f77ffe1337b69d64736f6c63430008180033";

type MockRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRegistry__factory extends ContractFactory {
  constructor(...args: MockRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockRegistry__factory {
    return super.connect(runner) as MockRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRegistryInterface {
    return new Interface(_abi) as MockRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockRegistry {
    return new Contract(address, _abi, runner) as unknown as MockRegistry;
  }
}
