/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as riskRouterSol from "./RiskRouter.sol";
export type { riskRouterSol };
export type { MockRegistry } from "./MockRegistry";
