/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "isRegisteredAgent" | "setRegistered"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isRegisteredAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistered",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "isRegisteredAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistered",
    data: BytesLike
  ): Result;
}

export interface MockRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MockRegistry;
  waitForDeployment(): Promise<this>;

  interface: MockRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isRegisteredAgent: TypedContractMethod<
    [agent: AddressLike],
    [boolean],
    "view"
  >;

  setRegistered: TypedContractMethod<
    [agent: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isRegisteredAgent"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setRegistered"
  ): TypedContractMethod<
    [agent: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
