export const ERR_JSON_PARSE = 'ERR_JSON_PARSE';
export const ERR_ENV_MISSING = 'ERR_ENV_MISSING';
export const ERR_KRAKEN_API_FAIL = 'ERR_KRAKEN_API_FAIL';
export const ERR_INVALID_SYMBOL = 'ERR_INVALID_SYMBOL';
export const ERR_MCP_FAIL = 'ERR_MCP_FAIL';
export const ERR_UNAUTHORIZED_AGENT = 'ERR_UNAUTHORIZED_AGENT';
export const ERR_PRICE_INVALID = 'ERR_PRICE_INVALID';
