/**
 * @title Generated Types (Spec-First)
 * @dev This file is automatically generated from .specify/spec/*.yaml
 * DO NOT EDIT MANUALLY.
 */

export interface TradeIntent {
  agentId: bigint;
  agentWallet: string;
  pair: string;
  action: string;
  amountUsdScaled: bigint;
  maxSlippageBps: bigint;
  nonce: bigint;
  deadline: bigint;
}

export interface Authorization {
  isAllowed: boolean;
  reason: string;
  signature: string;
}

export interface ValidationArtifact {
  intentHash: string;
  timestamp: bigint;
  status: 'AUTHORIZED' | 'REJECTED';
}

