/**
 * @title Generated Types (Spec-First)
 * @dev This file is automatically generated from .specify/spec/*.yaml
 * DO NOT EDIT MANUALLY.
 */

export interface TradeIntent {
  agentId: string;
  pair: string;
  volume: bigint;
  maxPrice: bigint;
  deadline: bigint;
}

export interface Authorization {
  isAllowed: boolean;
  reason: string;
}

export interface ValidationArtifact {
  intentHash: string;
  timestamp: number;
  status: 'AUTHORIZED' | 'REJECTED';
}
