import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

/**
 * @dev Spec-First Type Generator.
 * Transforms .specify/spec/*.yaml into TypeScript interfaces.
 */
function generateTypes() {
  const specDir = '.specify/spec';
  const outputFile = 'src/logic/generated_types.ts';
  const files = fs.readdirSync(specDir).filter(f => f.endsWith('.yaml'));

  let tsContent = `/**
 * @title Generated Types (Spec-First)
 * @dev This file is automatically generated from .specify/spec/*.yaml
 * DO NOT EDIT MANUALLY.
 */\n\n`;

  const seenEntities = new Set();

  for (const file of files) {
    const filePath = path.join(specDir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    const spec = yaml.load(content);

    if (spec.entities && Array.isArray(spec.entities)) {
      for (const entityObj of spec.entities) {
        for (const [name, definition] of Object.entries(entityObj)) {
          if (seenEntities.has(name)) continue;
          seenEntities.add(name);

          tsContent += `export interface ${name} {\n`;
          for (const [propName, propType] of Object.entries(definition)) {
            const typeStr = String(propType);
            let tsType = 'string';

            if (typeStr === 'bigint' || typeStr === 'int' || typeStr === 'uint256' || typeStr === 'uint' ||
                propName === 'deadline' || propName === 'volume' || propName === 'maxPrice' ||
                propName === 'agentId' || propName === 'amountUsdScaled' || propName === 'maxSlippageBps' ||
                propName === 'nonce' || propName === 'maxPrice') {
               tsType = 'bigint';
            } else if (typeStr === 'float' || typeStr === 'timestamp') {
               tsType = 'number';
            } else if (typeStr === 'bool' || typeStr === 'boolean') {
               tsType = 'boolean';
            } else if (typeStr === 'bytes32') {
               tsType = 'string';
            } else if (typeStr === 'address') {
               tsType = '`0x${string}`';
            } else if (propName === 'pair') {
               tsType = 'string';
            } else if (typeStr.includes('enum')) {
               const enumMatch = typeStr.match(/\[(.*?)\]/);
               if (enumMatch) {
                 tsType = enumMatch[1].split(',').map(s => `'${s.trim()}'`).join(' | ');
               }
            }

            tsContent += `  ${propName}: ${tsType};\n`;
          }
          tsContent += `}\n\n`;
        }
      }
    }
  }

  fs.writeFileSync(outputFile, tsContent);
  console.log(`✅ Generated types in ${outputFile}`);
}

generateTypes();
